version: "3.8"

services:
  py1:
    image: hardware-agent
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
  py2:
    image: hardware-agent
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
  py3:
    image: hardware-agent
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
  py4:
    image: hardware-agent
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
  py5:
    image: hardware-agent
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
